### ISSUE TITLE
[RFC] Documenting colorschemes 

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/ColorSchemes.jl#72]
Wondering if anyone has comments on the display of colorschemes; now that Documenter.jl can do multiple SVGs easily I've changed the code a bit.

Proposal:
<img width="1366" alt="PNG image 3" src="https://user-images.githubusercontent.com/52289/122641863-c0834b80-d0ff-11eb-87be-5550882cace0.png">

 https://juliagraphics.github.io/ColorSchemes.jl/latest/basics/#cmocean

**Comment by briochemc** [comment]
I have two uninvited comments! (I hope you don't mind 😃)

1. I actually almost started an issue to ask if somehow the colorscheme names could be actual text instead of inside an image (svg or not) so that they are easily searchable in the browser. Since you are thinking of revamping this part, I thought I'd mention it here 😃 

2. I just checked the dev-version of the docs and noticed that the new display has an issue for some of the colorscheme categories (but maybe this is just because it's a WIP, or maybe it's just on my side 🤔):
    

https://user-images.githubusercontent.com/4486578/124050623-425b6900-da5e-11eb-8149-4d27b78ec60c.mov

**Comment by cormullion** [comment]
Thanks! Yes I think it would be better with plain text and separate image swatches. 

SVGs are great until they get complicated - then browsers can start to choke.

**Comment by cormullion** [comment]
v3.13 has another attempt at the catalogue. Still work in progress I suppose...  :)

**Comment by briochemc** [comment]
Oh, that's nice! Although now that there's only one colormap displayed each time, maybe the entire width is too much? (BTW let me know if these uninvited comments are just useless noise and I'll stop!)

**Comment by cormullion** [comment]
(No, it's good to know that someone cares! 😃 )

I don't know - one person's "too much" is another persons "not enough"! I just went for the default width.

I'll check it out on mobile as well. Always room for improvements. If you want to try some tweaks, the code is stored in the head of "catalogue.md".

**Comment by briochemc** [comment]
> one person's "too much" is another persons "not enough"!

Sure, It's just that it used to be 2 colormaps (continous and categorical) on the same line so they used to display with half the width and it sort-of struck me that they looked too big. FWIW, this is a side to side (well top to bottom) comparison with matplotlib's colormaps display on their website:

<img width=80% alt="Screen Shot 2021-07-08 at 8 04 59 pm" src="https://user-images.githubusercontent.com/4486578/124904082-fabd7a00-e027-11eb-9bd0-569fb22641ed.png">
<img width=80% alt="Screen Shot 2021-07-08 at 8 05 25 pm" src="https://user-images.githubusercontent.com/4486578/124904118-00b35b00-e028-11eb-9afb-df12edf42aa7.png">

> I'll check it out on mobile

Do people... make plots on mobile? That seems like a very niche use!
